add policy for CIS-1.1 - 4.03 Ensure "Block Project-wide SSH keys" is enabled for VM instances
GoogleCloudPlatform/policy-library pull request #401
Opened 2021-08-17 06:37 UTC by palani-ram-google-partner

add policy for CIS-1.1 - 4.03 Ensure "Block Project-wide SSH keys" is enabled for VM instances

2021-08-17 06:39 UTC, palani-ram-google-partner commented
@morgante , Please review this PR and let me know if there is any issue or good to merge.

2021-08-17 07:56 UTC, morgante requested changes
Thanks for contributing.

2021-08-17 07:56 UTC, morgante commented on policies/templates/gcp_compute_block_ssh_keys_v1.yaml
> +        openAPIV3Schema:
We should still specify a schema, but with no properties. cf. https://github.com/GoogleCloudPlatform/policy-library/blob/master/policies/templates/gcp_gke_dashboard_v1.yaml#L28

2021-08-17 07:56 UTC, morgante commented on policies/templates/gcp_compute_block_ssh_keys_v1.yaml
> +        #ENDINLINE
Nit: Please include a newline at the end of files.

2021-08-17 07:56 UTC, morgante commented on samples/compute_block_ssh_keys.yaml
> +    description: CIS-1.1 - 4.03 Ensure "Block Project-wide SSH keys" is enabled for VM instances
CIS constraints should follow the existing annotation standard.

https://github.com/GoogleCloudPlatform/policy-library/blob/master/samples/compute_forbid_ip_forward.yaml#L20

2021-08-17 07:56 UTC, morgante commented on validator/compute_block_ssh_keys.rego
> +	metadata_config.items[i].key == "block-project-ssh-keys"
Unfortunately the logic for this isn't quite right. If `block-project-ssh-keys` isn't set at all, this `deny` condition will never occur.

What you probably need to do is add an additional function like this:

```
default metadata_blocks_project_keys(meta) = false
metadata_blocks_project_keys(meta) = true {
  metadatum := meta.items[_]
  metadatum.key == "block-project-ssh-keys"
  metadatum.value == "true"
}
```

Then within the core `deny` block you just call it:
```
  not metadata_blocks_project_keys(metadata_config)
```

2021-08-17 07:56 UTC, morgante commented on validator/compute_block_ssh_keys.rego
> +	metadata_config := lib.get_default(instance, "metadata", {})
You should include an empty items list by default.

```suggestion
	metadata_config := lib.get_default(instance, "metadata", {"items": []})
```

2021-08-17 07:56 UTC, morgante commented on validator/compute_block_ssh_keys_test.rego
> +find_violations[violation] {
Please use the new test utils. Example: https://github.com/GoogleCloudPlatform/policy-library/blob/master/validator/enforce_labels_test.rego#L19-L20

2021-08-17 07:56 UTC, morgante commented on validator/compute_block_ssh_keys_test.rego
> +# Confim no violations with no instances
For test cases, please test the following scenarios:

1. No instances at all
2. One instance with the correct key, one without
3. No instances with the correct key
4. An instance without metadata configured at all (`metadata_config` doesn't exist).

2021-08-17 07:56 UTC, morgante commented on validator/test/fixtures/compute_block_ssh_keys/constraints/block_ssh_keys_default/data.yaml
> +  parameters: { }
```suggestion
  parameters: {}
```

2021-10-12 08:46 UTC, palani-ram-google-partner commented
@morgante 
We can close this PR. We do not need to merge this PR.

Created a new PR with these review comments fixed.
https://github.com/GoogleCloudPlatform/policy-library/pull/405

2021-10-12 21:37 UTC, closed without merging