feat:adds 5 additional constraints to the gke hardening bundle
GoogleCloudPlatform/policy-library pull request #424
Opened 2022-03-05 02:08 UTC by g-awmalik

- new bundle create for gke-hardening i.e. gke-hardening-v2022.03
- fixes for missed documentation
- minor update the generate_docs fn to support `kpt fn eval`

2022-03-05 02:08 UTC, g-awmalik commented
@morgante - please take a look

2022-03-07 18:15 UTC, morgante requested changes

2022-03-07 23:13 UTC, g-awmalik commented on docs/bundles/gke-hardening-v2022.03.md
> +# gke-hardening-v2022.03
Sure. Updated the name.

2022-03-07 23:25 UTC, morgante approved these changes

2022-03-07 23:25 UTC, merged